slam_toolbox:
  ros__parameters:
    use_sim_time: false

    # Frames
    map_frame: map
    odom_frame: odom
    base_frame: base_link
    scan_topic: /scan

    # Mode
    mode: mapping
    use_odom: true
    
    transform_publish_period: 0.02
    map_update_interval: 2.0
    resolution: 0.05
    max_laser_range: 12.0
    minimum_time_interval: 0.1
    
    use_scan_matching: true
    minimum_travel_distance: 0.02
    minimum_travel_heading: 0.02
    scan_buffer_size: 20
    scan_buffer_maximum_scan_distance: 15.0
    
    loop_search_maximum_distance: 3.0
    do_loop_closing: true

