ekf_filter_node:
  ros__parameters:

    enabled: true

    frequency: 30.0
    sensor_timeout: 1.0
    two_d_mode: true
    transform_time_buffer: 0.1

    odom0: /odom
    odom0_config: [true,  true,  false,
                   false, false, true,
                   false, false, false]
    odom0_queue_size: 5

    publish_tf: true
    predict_to_current_time: true 
  
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
    world_frame: odom
