ekf_filter_node:
  ros__parameters:
    frequency: 30.0
    sensor_timeout: 1.0
    two_d_mode: true
    transform_time_buffer: 0.1
    odom0: /odom_raw
    odom0_config: [true,  true,  false,
                   false, false, true,
                   false, false, false]
    odom0_queue_size: 5
    # If you have IMU, uncomment imu0 and imu0_config
    # imu0: /imu/data
    # imu0_config: [false, false, false,
    #               true,  true,  true,
    #               false, false, false]
    publish_tf: true
    map_frame: map
    odom_frame: odom
    base_link_frame: base_link
